### ISSUE TITLE
æ

### ISSUE THREAD

**Issue by raynei86** [awful-coder/awful-coder.github.io#1]
æææææææ
6942

**Comment by datrandomboi** [comment]
dude what

**Comment by raynei86** [comment]
![mountain-lake-scenery-nature-cottage-25-4K](https://user-images.githubusercontent.com/68117897/101987868-92124880-3c64-11eb-9f79-717228003032.jpg)

**Comment by datrandomboi** [comment]
### i-
![Screenshot 2020-12-07 152415](https://user-images.githubusercontent.com/64981373/101988121-cf2b0a80-3c65-11eb-8cc8-c6889dfc4615.png)

**Comment by raynei86** [comment]
`cout << "No curly braces make me uncomfortable" << endl;`

**Comment by datrandomboi** [comment]
`print(ahahahahahaha)`

**Comment by raynei86** [comment]
`cout << "STOP IGNORING SEMICOLONS AND DOUBLE QUOTES" << endl;`

**Comment by datrandomboi** [comment]
asnwer = input("what is a cout")

**Comment by raynei86** [comment]
`cout << "cout is print in c++" << endl;`
`printf("%s", "I can also use printf if that makes you more comfortable lol");`

**Comment by datrandomboi** [comment]
`System.out.println("c and c++ is weird");`
`Console.WriteLine("i dont like them");`
`console.write("i use javascript sometimes (but eww the js syntax sucks)");`
`print("and python is my main language")`
`answer = input(">>> ")`

**Comment by raynei86** [comment]
`cout << "c and c++ kinda weird but python is literally english" << endl;`

**Comment by datrandomboi** [comment]
`<p>no u</p>`

**Comment by raynei86** [comment]
who is this person that made the repo anyways

**Comment by datrandomboi** [comment]
<a href="https://pastebin.com/YdFYjJPR">wait look at this first</a>

**Comment by raynei86** [comment]
> [wait look at this first](https://pastebin.com/YdFYjJPR)

paste not found man

**Comment by datrandomboi** [comment]
wait what

**Comment by raynei86** [comment]
![image](https://user-images.githubusercontent.com/68117897/101990112-d278c300-3c72-11eb-8e0d-e8c1a69436f4.png)

**Comment by datrandomboi** [comment]
i am aware

**Comment by datrandomboi** [comment]
> who is this person that made the repo anyways

a friend

**Comment by raynei86** [comment]
@datrandomboi say thanks to your mom for me she said my pic was nice lol

**Comment by datrandomboi** [comment]
<button onclick="window.location.replace('https://www.google.com')">test</button>
